#!/bin/bash
UHOME="/home"
FILE="/home/kali/GenCyber"
FILENAME="GenCyber"
 # get list of all users
_USERS="$(awk -F':' '{ if ( $3 >= 500 ) print $1 }' /etc/passwd)"
for u in $_USERS
do
   _dir="${UHOME}/${u}"
   if [ -d "$_dir" ]
   then
      chown -R $(id -un $u):$(id -gn $u) "$_dir/${FILENAME}"
   fi
done
